# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "./yarn.lock" }}
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn stylelint
      - save_cache:
          key: dependency-cache-{{ checksum "./yarn.lock" }}
          paths:
            - ./node_modules
            - ./.next/cache

  build:
    docker:
      - image: circleci/node:12
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build . -t $DOCKER_USER/next-dict:${CIRCLE_BRANCH}
      - run: docker push $DOCKER_USER/next-dict:${CIRCLE_BRANCH}

  deploy:
    machine: true
    steps:
      - run: ssh admin@nless.pro "docker pull $DOCKER_USER/next-dict:${CIRCLE_BRANCH}; docker kill next-dict || true; docker rm next-dict || true"
      - run: ssh admin@nless.pro "docker run --name next-dict --restart always -d -p 3007:3007 -v /home/admin/docker/bindmount/next-dict/.env:/usr/src/app/.env -v /home/admin/docker/bindmount/next-dict/db:/usr/src/app/src/server/static/data $DOCKER_USER/next-dict:${CIRCLE_BRANCH}"

  cleanup:
    machine: true
    steps:
      - run: ssh admin@nless.pro "docker image prune -f"

workflows:
  version: 2

  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - cleanup:
          requires:
            - deploy
